stage1:
  base_lr: 0.00005
  disc_lr: 0.0001
  perceptual_weight: 0.002
  adv_weight: 0.005
  kl_weight: 0.00000001
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: [64, 128, 128, 128]
    latent_channels: 3
    num_res_blocks: 2
    attention_levels: [False, False, False, False]
    with_encoder_nonlocal_attn: True
    with_decoder_nonlocal_attn: True

discriminator:
  params:
    input_nc: 1
    ndf: 64

perceptual_network:
  params:
    spatial_dims: 2
    network_type: "squeeze"
